name: mern-auth

services:
  mongo:
    image: mongo:7.0.12
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-auth

  api:
    build:
      context: ./server
      target: production
    restart: unless-stopped
    env_file: ./server/.env
    networks:
      - mern-auth
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - mern-auth
    depends_on:
      - api

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern-auth
    depends_on:
      - api
      - client

volumes:
  mongo_data:
  caddy_data:
  caddy_config:

networks:
  mern-auth:
    driver: bridge
